version: '2'

services:
  master:
    image: zhangxianguo/j-base
    command: master
    tty: true
    ports:
      - "60000"
    volumes:
      - "./test/:/jmeter/sample/"
    networks:
      - jmeter-network
      
  server:
    image: zhangxianguo/j-base-slave
    tty: true
    ports:
      - "50000"
      - "1099"
    networks:
      - jmeter-network
    depends_on:
      - master

networks:
  jmeter-network: